### PR TITLE
Spacy v3 migration

### PR DESCRIPTION
**Pull request by kavorite**
I love the results of YAKE, but I also really love the results of using transformer models, so I figured I would make it easier for consumers of this library to have both

I _think_ it should be backward-compatible with spacy v2, but I'm not sure, because the `Language.factory` decorator seems to have lived somewhere else, and I _really_ don't feel like wrangling `Pipenv` to convince it to reload spacy v2 and check for me

something I considered porkbarreling into the work I did on this topic branch was adding another candidate extractor for full sentences so that this package can double as a summarizer, but I decided not to, because I think that's out of scope for this work and I'm not sure how much effort it would take

### CODE REVIEW

**Comment by talmago** [comment]
@kavorite Thanks for this great work !! I never published this package since it was lacking unit testing and CI/CD for the purpose of releasing this package, so i'm quite open to break its parts and re-build it in a way that would be more convenient for potential users. 

I might be missing something, but the main idea of the original implementation was to separate the "tokenization" process (ngrams vs. chunks vs. any callable object which maps the object to a list of candidates), from the keyword extraction algorithm itself (i.e yake). Is this still in mind within the new implementation?

**Comment by kavorite** [comment]
Yeah, that was one of the main motivations of making separate pipeline components-- I didn't like having all that functionality encapsulated in the same base class, I thought it'd make the code more extensible and composable if we just required a separate pipeline component to set `kw_candidates` from descendants of `base.KeywordExtractor`

this way user could develop their own approach to setting `doc._.kw_candidates` components, too, the process isn't so completely opaque to consumers of the package that they can't impose their own rules for filtering candidate keywords-- and I thought it would make it easier to maintain, as well, because this way, my hope was that we could avoid configuring the candidate selection via the same interface that we configure the keyword extractor

now, spaCy handles that for us because the parameters are all given as arguments to the extractor and selector initializers separately-- all I did was split those two bits of functionality into separate base class hierarchies because I thought it was crucial to preserve separation of those concerns and also that it might be nice if a consumer could exert control over that aspect of the process

I just didn't want the interface to get more complicated, so I also made sure that if you didn't explicitly configure a candidate selection component, since the implementations you've given were already opinionated about their candidate selection and specified defaults anyway, I just made them put those in the pipeline upon component initialization if no candidate selector is found

**Comment by talmago** [comment]
@kavorite Some of your comments about the initial design are valid, and i made an effort to address them in my recent changes to the project. 

Overall, i'd like to keep the usage as been demonstrated in this [example](https://github.com/talmago/spacy_ke#usage-as-a-spacy-pipeline-component). Btw, the idiom was adapted from other projects in the spacy universe such as `pysbd`. I also don't think there is a real need to load a component for a pre-step of candidate selection. In the new implementation, it's possible to "load" the candidate selection from registry (catalogue), which is btw another idiom taken from the spacy universe (See [sense2vec](https://github.com/explosion/sense2vec)). It's also possible to declare a function for candidate selection, push it to registry (by simply using a python decorator) and load it at runtime. 

Following your PR i'm going to explore the spaCy v3 and see how it can be integrated with out compromising the v2.X.X versions, which I currently use in several of my projects. Hopefully, this should be ready soon.

**Comment by kavorite** [comment]
Excited to see how you realize the configuration deltas, it's not super important to me that my own code gets main-lined, I realize that big deviations from the public interface that you wanted to expose before are not desirable

nothing prevents me from using my own fork 

but I'll also mention that the example you referenced isn't compromised by the internal changes I made to the library on my branch to the best of my knowledge, you'd just have to use pipeline component names instead of adding them to the pipeline in user code by importing and instantiating the respective classes

**Comment by talmago** [comment]
@kavorite

With spaCy 3.0 it would like this to get what you suggested: 

```python
@Language.factory("yake", default_config={
    "window": 2,
    "lemmatize": False,
    "candidate_selection": "ngram"
})
def yake(nlp, name, window: int, lemmatize: bool, candidate_selection: str):
    return Yake(nlp, window=window, lemmatize=lemmatize, candidate_selection=candidate_selection)
```

Notice that the value "ngram" is a key in the [catalogue](https://pypi.org/project/catalogue/). User can choose to change this value to "foo" while being responsible to populate the registry with this method. 

I created a [tracker](https://github.com/talmago/spacy_ke/issues/2) for spacy v3.0 support, but as pointed out i'm using this library in some production environments with spaCy 2.x and therefore can't accept this change.

**Pull request closed without merging**
